# Generated by Django 5.1.7 on 2025-03-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
