# Generated by Django 5.1.7 on 2025-03-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userextra_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextra',
            old_name='verify',
            new_name='verifyed',
        ),
    ]
