# Generated by Django 5.1.7 on 2025-03-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_verify_userextra_verifyed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextra',
            old_name='verifyed',
            new_name='verified',
        ),
    ]
