# Generated by Django 5.1.7 on 2025-03-21 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_address_id_userextra_id_alter_address_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
