# Generated by Django 5.1.7 on 2025-03-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_address_id_remove_userextra_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='area',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='landmark',
        ),
    ]
