# Generated by Django 5.1.7 on 2025-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_address_email_address_full_name_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
