# Generated by Django 5.1.7 on 2025-03-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userextra',
            name='forgot_password_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
