# Generated by Django 5.1.3 on 2025-03-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userextra_forgot_password_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='change_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
