# Generated by Django 5.1.7 on 2025-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
