<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-03-22 11:36
=======
# Generated by Django 5.1.7 on 2025-03-22 11:31
>>>>>>> dc39fb9606eb59e1a78e2def5e3af9088572fd57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productcategory_slug_productsubcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
