# Generated by Django 5.1.7 on 2025-03-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productcategory_slug_productsubcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
