# Generated by Django 5.1.3 on 2025-03-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_stock_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images'),
        ),
    ]
