# Generated by Django 5.1.7 on 2025-03-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productcategory_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_quanitity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
