# Generated by Django 5.1.7 on 2025-03-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_images'),
        ('shop', '0007_alter_product_price'),
    ]

    operations = [
    ]
