# Generated by Django 5.1.7 on 2025-03-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='icon',
            field=models.CharField(choices=[('fa fa-check', 'fa fa-check'), ('fa fa-times', 'fa fa-times'), ('fa fa-star', 'fa fa-star'), ('fa fa-heart', 'fa fa-heart')], default='fa fa-check', max_length=50),
        ),
    ]
