# Generated by Django 5.1.7 on 2025-03-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_whislist_added_at_alter_whislist_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whislist',
            name='added_at',
        ),
        migrations.AlterField(
            model_name='whislist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whishlist_product', to='shop.product'),
        ),
    ]
