# Generated by Django 5.1.7 on 2025-03-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='costomer',
            new_name='customer',
        ),
    ]
