# Generated by Django 5.1.7 on 2025-03-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_address'),
        ('orders', '0014_alter_order_address'),
    ]

    operations = [
    ]
