# Generated by Django 5.1.7 on 2025-04-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userextra_change_password_token'),
        ('orders', '0017_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='account.userextra'),
        ),
    ]
