# Generated by Django 5.1.7 on 2025-04-05 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_cart_customer'),
        ('shop', '0018_product_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonUserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('order_taken', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Non User Cart',
                'verbose_name_plural': 'Non User Carts',
            },
        ),
        migrations.CreateModel(
            name='NonUserCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.nonusercart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_cart', to='shop.product')),
            ],
        ),
    ]
