# Generated by Django 5.1.7 on 2025-04-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_nonusercart_nonusercartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonusercart',
            options={},
        ),
    ]
