# Generated by Django 5.1.7 on 2025-04-05 19:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_nonusercart_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonusercart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nonusercartitem',
            name='id',
        ),
        migrations.AddField(
            model_name='nonusercart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonusercart',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='nonusercart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nonusercartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonusercartitem',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='nonusercartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
