# Generated by Django 5.1.7 on 2025-04-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_nonusercart_id_remove_nonusercartitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
