# Generated by Django 5.1.7 on 2025-04-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_address_session_key_alter_address_user'),
        ('orders', '0025_alter_nonusercart_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.address'),
        ),
    ]
